### ISSUE TITLE
Repository - EGAD00001002680 Adrenocortical carcinoma RNA-seq

### ISSUE THREAD

**Issue by klearned** [UCSC-Treehouse/operations#23]
Original paper: [PMC4352712](http://europepmc.org/articles/PMC4352712)
From: St Jude (via EGA [EGAD00001002680](https://www.ebi.ac.uk/ega/datasets/EGAD00001002680) )
Detailed file spreadsheet: [EGAD00001002680 PCGP: Adrenocortical carcinoma RNA-seq](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1ypbs6a-9JP30Qwt9zFlVIyWjOz45L_3hNxVFjx5cYjA/edit?usp=sharing)

19 individuals, but n= 21 samples
Note, these data are **paired-end**

**Task List:**
- [x] Request permission
- [x] Download & decrypt data
- [x] Convert bam to fastq
- [ ] Core (RNAseq Pipeline + QC)

**Important paper excerpts:**

> **Abstract**
> Pediatric adrenocortical carcinoma is a rare malignancy with poor prognosis. Here we analyze 37 adrenocortical tumors (ACTs) by whole genome, whole exome and/or transcriptome sequencing. Most cases (91%) show loss of heterozygosity (LOH) of chromosome 11p, with uniform selection against the maternal chromosome. IGF2 on chromosome 11p is overexpressed in 100% of the tumors. TP53 mutations and chromosome 17 LOH with selection against wild-type TP53 are observed in 28 ACTs (76%). Chromosomes 11p and 17 undergo copy-neutral LOH early during tumorigenesis, suggesting tumor-driver events. Additional genetic alterations include recurrent somatic mutations in ATRX and CTNNB1 and integration of human herpesvirus-6 in chromosome 11p. A dismal outcome is predicted by concomitant TP53 and ATRX mutations and associated genomic abnormalities, including massive structural variations and frequent background mutations. Collectively, these findings demonstrate the nature, timing and potential prognostic significance of key genetic alterations in pediatric ACT and outline a hypothetical model of pediatric adrenocortical tumorigenesis.

> **Patient Samples**
> ...Six samples of normal adrenocortical tissue obtained during nephrectomy for Wilms tumor were used as controls in gene expression studies as well 16 tumor samples studied in WGS cohort. 

> **Transcriptome sequencing**
> For library construction, 2–5 μg of total RNA was extracted from tumor samples by using Qiagen RNeasy Mini kits according to the manufacturer’s instructions. RNA concentration was measured by using a NanoDrop 100 Spectrophotometer (Thermo Scientific). RNA integrity was measured by using an Agilent Technologies 2100 Bioanalyzer Lab-on-a-chip system. Total RNA was treated with DNAse I (Invitrogen) and enriched for poly A containing mRNA using oligo dT beads (Dynabeads, Invitrogen). The cDNA synthesis used random hexamers and the Superscript Double- Stranded cDNA Synthesis kit (Invitrogen). Paired-end reads from mRNA-seq were aligned to the following 4 database files by using a Burrows-Wheeler Aligner (0.5.5)45 (i) human NCBI Build 37 reference sequence, (ii) RefSeq, (iii) a sequence file representing all possible combinations of non-sequential pairs in RefSeq exons, and (iv) AceView database flat file downloaded from UCSC, representing transcripts constructed from human expressed sequence tag (EST). The mapping results from databases (ii)–(iv) were aligned to human reference genome coordinates. The final BAM file (compressed binary version of the Sequence Alignment/Map [SAM] format) file was constructed by selecting the best alignment in the four databases. RNA expression level was measured by fragments per kilobase of transcript per million fragments mapped (FPKM)46. SVs were detected by using the CIRCERO algorithm, a novel algorithm that uses de novo assembly to identify structural variation in RNA-seq data (unpublished data). The structural variants detected in RNA-seq data were validated with MiSeq sequencing. Primer pairs were designed (with Primer3) to bracket the genomic regions containing putative structural variations. The structural variations found by RNA-seq are reported in Supplementary Table 4.
>

**Comment by hbeale** [comment]
@klearned linh observes that these are paired end. we'll update you here.

**Comment by klearned** [comment]
@hbeale OK, thank you for keeping me updated!
@linhvoyo Thank you for catching that!

Maybe I am misunderstanding what the EGA field "Library Layout" is OR they get it wrong often?

**Comment by hbeale** [comment]
@klearned  I don't think you're misunderstanding. @linhvoyo  and I are working on a process where all bam files are converted the same way, and the ended-ness is detected from the data rather than EGA.

**Comment by klearned** [comment]
@hbeale that is great since the EGA doesn't seem that reliable! Thanks Holly and @linhvoyo!

**Comment by klearned** [comment]
@hbeale and @linhvoyo 
I preparing to pass this on to Treeshop today, but I think I now need to wait until the fastq files can be re-done as paired-read samples (2 files per sample instead of just 1)? Is that right?

**Comment by hbeale** [comment]
yes.

**Comment by klearned** [comment]
@linhvoyo Hmm, the ones that needed conversion to fastq were EGAD00001002680 (on this ticket) and EGAD00001001098. For EGAD00001001666, I hadn't finished downloading the data yet.

**Comment by klearned** [comment]
@rcurrie  I am prepping the manifest for this dataset, EGAD0000100268, and remembered that the way the .bam files were named by the download program gave each .bam file a leading underscore (first character of the filename is "_") and so the fastqs now have this name. It struck me as annoying at first, but I just realized it could be a problem. Is this going to be OK or do these need to have the leading underscore removed from the filename before sending to Treeshop?

For example:

`/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/data/fastq/_EGAR00001470676_SJACT071_D-D16FGACXX.5.r1.fq.gz`

`/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/data/fastq/_EGAR00001470676_SJACT071_D-D16FGACXX.5.r2.fq.gz`

**Comment by klearned** [comment]
If the sample/filename leading underscore is OK (see comment above) then this dataset EGAD00001002680 is ready for Treeshop (RNA-seq + QC). 
n=21 samples and all are paired-end (from 19 donors).

**Manifest**:
`/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/data/fastq/manifestRnaSeqEGAD00001002680`

**Comment by rcurrie** [comment]
Running...

**Comment by rcurrie** [comment]
@klearned files have to be R1/R2, capitals, sorry!

https://github.com/BD2KGenomics/toil-rnaseq

Samples consisting of tarballs with fastq files inside must follow the file name convention of ending in an R1/R2 or _1/_2 followed by .fastq.gz, .fastq, .fq.gz or .fq..

**Comment by klearned** [comment]
@rcurrie OK, thank you for this info

@linhvoyo  Could you make the changes Rob describes above to these samples in this dataset and these other EGA datasets: 

EGAD00001002680 #23 (this ticket)
EGAD00001001098 #22 
EGAD00001001666 #27 (ready for conversion)

**Comment by linhvoyo** [comment]
Hi all. 
I fixed EGAD00001002680 and EGAD00001001098.

@klearned Will make changes to EGAD00001001666 once I'm done processing them.

**Comment by klearned** [comment]
Thank you!

**Comment by rcurrie** [comment]
I'm going to see about coding up something in treeshop to handle this as the other one is 100+ samples, so standby on finishing up EGAD00001001666 @linhvoyo

**Comment by rcurrie** [comment]
Running...

**Comment by rcurrie** [comment]
Ruh Roh:
[104.40.71.126] out: 552d3d7e8438: 2016-12-18 04:40:30,083 WARNING: toil.leader: y/l/jobhPDQvL: cutadapt: error: Re
ads are improperly paired. Read name 'HWUSI-EAS1714_17:6:100:16651:9081' in file 1 does not match 'HWUSI-EAS1714_17
:6:100:1665:19081' in file 2.

Files:
/pod/pstore/groups/treehouse/publisheddata/stjude/EGAD00001002680/data/fastq/_EGAR00001470655_SJACT001_D-638PHAAXX.6.R1.fq.gz
/pod/pstore/groups/treehouse/publisheddata/stjude/EGAD00001002680/data/fastq/_EGAR00001470655_SJACT001_D-638PHAAXX.6.R2.fq.gz

**Comment by linhvoyo** [comment]
@rcurrie - something is up with the sorting. I'm currently looking into it

**Comment by adurbin2** [comment]
@linhvoyo @rcurrie do we have any new information on this dataset? thank you --

**Comment by linhvoyo** [comment]
@adurbin2 

@rcurrie I've figured out what is wrong with that one. For now just process the rest of the batch, I will reconvert any files that failed later. Thanks

**Comment by klearned** [comment]
Thanks all!!

**Comment by rcurrie** [comment]
@cygao we should run these through the core instead of Treeshop

**Comment by cygao** [comment]
@rcurrie does this mean we should wait until the test batch is verified?

**Comment by rcurrie** [comment]
Yes, you can get the manifest all ready but let's wait to upload until we get the word that EGAD1098 worked, at least for the first set of 4.

**Comment by adurbin2** [comment]
@linhvoyo @klearned Linh, Katrina is wondering if this batch will also need to be re-converted due to the the unpaired reads bug? Can you tell from the date? thanks

**Comment by linhvoyo** [comment]
@klearned @adurbin2 I think so not too sure honestly. I think this is when I figured out that there was a bug in the old script.

**Comment by linhvoyo** [comment]
@klearned @adurbin2 I can check the log. Can I the location to this dir

**Comment by adurbin2** [comment]
@klearned Maybe best to re-convert then - @linhvoyo Are we still using the v2 you trained us on?

**Comment by linhvoyo** [comment]
@klearned  yes V2 is the one w/o the bug

**Comment by klearned** [comment]
@linhvoyo <https://github.com/linhvoyo> The fastqs are here if you want to
check to see which version they were run on.

/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/fastq


Looking at the earlier comments in this tickets, it looks like maybe this
is one that you noticed the bug on? Maybe you can check to see what you
think?
https://github.com/UCSC-Treehouse/operations/issues/23#issuecomment-265295931

**Comment by klearned** [comment]
Also, I wonder if there is some sort of .txt file that the docker process could leave that lists the version that was run to convert the bams to fastq? Maybe it already does that?

**Comment by linhvoyo** [comment]
@klearned These were processed with the version 2. I cat the log in /pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/fastq directory.

I used this command line, 
for i in *.fq;do   cat $i | perl scripts/mergelines.pl | sort --stable -t $'\t' --parallel=10 -T ./temp -S 10G | uniq | perl scripts/splitlines.pl > $i.perl; done, for conversion. Yep, this is the version two

**Comment by linhvoyo** [comment]
@klearned That's a good idea. I can add something in the docker that prints out which version you're running.

**Comment by klearned** [comment]
@linhvoyo OK, great! So, to clarify, these do **not** need to be reconverted from bam to fastq, correct?

**Comment by linhvoyo** [comment]
@klearned affirmative

**Comment by klearned** [comment]
@hbeale I am having an issue with the manifest on this one. I am describing my issue below so I don't forget it, but it would probably be easiest for me to explain in person tomorrow. Then we can make a determination on how to proceed. Thanks!

The first 3 samples are from the same patient, but I am not sure if they should be run as a "bundle" (i.e. combined):
_EGAR00001470655_SJACT001_D-638PHAAXX.6
_EGAR00001470656_SJACT001_D-638PHAAXX.7
_EGAR00001470657_SJACT001_D-D0AHNACXX.1

The last part of the 3rd one is different: D0AHNACXX.1 vs. 638PHAAXX.6, which messes up our current method of coming up with the the sample ID for the manifest (which needs to be the same for bundled samples). We've been using: ACT001_D-638PHAAXX, but this would leave two different  Sample Ids for this set of three: ACT001_D-638PHAAXX and ACT001_D-D0AHNACXX. We can just make this one shorter, ACT001_D, but I am wondering if this really is three runs of a single sample or not. 

According to the metadata, all three are from the same sample Sample Accession field, they are from the same sample, but I don't know how much to trust the metadata: 

```
Sample ID				Donor Id	Sample Accession ID	Run Accession ID	Experiment ID
_EGAR00001470655_SJACT001_D-638PHAAXX.6	RNA-Seq-SJACT001_D	EGAN00001428190	EGAR00001470655	EGAX00001433203
_EGAR00001470656_SJACT001_D-638PHAAXX.7	RNA-Seq-SJACT001_D	EGAN00001428190	EGAR00001470656	EGAX00001433203
_EGAR00001470657_SJACT001_D-D0AHNACXX.1	RNA-Seq-SJACT001_D	EGAN00001428190	EGAR00001470657	EGAX00001433203
```

**Comment by hbeale** [comment]
Hi Katrina--

In this case, I believe the metadata. D0AHNACXX.1 and 638PHAAXX.6 are flow
cell IDs, with 1 and 6 indicating the respective lanes on those flowcells
(For details, see the second table in the "Illumina sequence identifier"
section of  https://en.wikipedia.org/wiki/FASTQ_format. What's not included
there and is the key here is this: Illumina flowcell IDs nearly always end
in XX. In this context, I first suspect any nine-character string ending in
XX of being a flowcell ID, especially if it's following by a single number
between 1 and 8. AFAIK, the max number of lanes per flowcell is 8.)

Since the same samples can be run on different flow cells, I support your
proposal of making the ID shorter ACT001_D, and more generally excluding
the flow cell ID from the sample ID. If sample ID needs to be globally
unique, I'd go with the EGA sample ID EGAN00001428190 or concatenating it
EGAN00001428190_SJACT001_D.

Best,
Holly

**Comment by klearned** [comment]
@hbeale Thanks so much for this clear explanation! I am really relieved
there is a clear explanation. I'll shorten the id to remove the flowcell
IDs for these so the three will be able to run as a single bundle. Thanks
again!

**Comment by klearned** [comment]
Here is the manifest for this one:
[EGAD00001002680 manifest](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1o2nivDfwlAku9xfa28o5-IhVRxkjSMyvzs4ySalB2Cs/edit?usp=sharing)

**Comment by klearned** [comment]
@adurbin2 OK, the [manifest](https://docs.google.com/spreadsheets/d/1o2nivDfwlAku9xfa28o5-IhVRxkjSMyvzs4ySalB2Cs/edit#gid=1977288675) for this dataset is also now ready for Treehouse IDs. Thank you!!

**Comment by adurbin2** [comment]
Done! And I think Holly's prior comment (I just read it) actually answers my question about the first patient - it's just one sample with six fastqs. So I have removed the colors and resolved my comment.

**Comment by klearned** [comment]
OK, the manifest is ready.
I asked Linh to give group write permissions on the files, then I can create the hard links, which will be here: /pod/pstore/groups/treehouse/for_core/THR10

**Comment by klearned** [comment]
files needing permission change are here:
/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001002680/fastq

**Comment by e-t-k** [comment]
@klearned I changed the perms, let me know if it didn't work (not sure if you need folder perms or just the files.)

`chmod g+w *.gz`

**Comment by klearned** [comment]
It worked!! Thanks @e-t-k !

**Comment by klearned** [comment]
OK, these are ready now, too!

**Comment by klearned** [comment]
Started uploading this dataset an hour or so ago.

**Comment by klearned** [comment]
@linhvoyo and @hbeale 
We ran these through the Core and they all "failed in 'cutadapt', which Walt states indicates that the read pairs are mismatched in the input files. According to the exchange earlier in this ticket (see attached screenshot), these files were converted with V2 of the bam to fastq conversion docker and so already had mismatched reads removed (and wouldn't fail in cutadapt). However, since they all failed due to cutadapt, I am wondering if there is an issue with the removal of the mismatched reads in the docker, or if these weren't run by the fixed docker (V2) as we thought? I am thinking the former since, _some_ of  EGAD00001001666 (#27) also failed cutadapt even though I definitely deleted all the original fastqs and re-converted them with the new V2 conversion docker ([see this comment](https://github.com/UCSC-Treehouse/operations/issues/27#issuecomment-276894463)).

Interestingly, none of the EGAD00001001098 (#22), which also originally had cutadapt errors since they were converted by the first version, failed in cutadapt. After the docker was fixed, I deleted the old fastqs and re-converted them with the V2. Note, this (EGAD00001001098) was the dataset that the issue was found on though, so perhaps the fix applies perfectlly to this dataset but another unforseen rendition of the mismatched reads wasn't addressed and is affecting the other two datasets?

I know this is a bunch of info, but just trying to give you the whole picture! I haven't downloaded the output yet. Let me know if this is necessary to track down this issue.

For more info on the exact errors, see the attached pdf of Walt's email which includes that info.

<img width="653" alt="screen shot 2017-03-14 at 10 39 47 pm" src="https://cloud.githubusercontent.com/assets/23464751/23935179/a7a4cb3a-0907-11e7-8f7d-2ba524ba1479.png">

[WaltEmailReFailingDatasets.pdf](https://github.com/UCSC-Treehouse/operations/files/843562/WaltEmailReFailingDatasets.pdf)

**Comment by linhvoyo** [comment]
@klearned @hbeale i will look into this and get back to you

**Comment by linhvoyo** [comment]
@klearned do you have the error message from cut adapt?

**Comment by linhvoyo** [comment]
@klearned This is great. Thank you

**Comment by linhvoyo** [comment]
@klearned sorry for bugging you again :( 
Can you point to the fq files? I did a search for THR10_0228_S01 but no luck.

**Comment by klearned** [comment]
@linhvoyo The fastq files are hard linked using their Treehouse Ids here: 
/pod/pstore/groups/treehouse/for_core/THR10

**Comment by adurbin2** [comment]
Sorry, that was an oops on my part. But, oddly, I can't see into that folder, or cd into it either. Is it because of permissions, or hard links, or...?

**Comment by klearned** [comment]
@adurbin2 Are you referring to this folder:
/pod/pstore/groups/treehouse/for_core/THR10

I just double-checked the permissions and it seems you should be able to get into it.

**Comment by linhvoyo** [comment]
I couldn't get in also 

-bash-4.2$ cd /pod/pstore/groups/treehouse/for_core/THR10
-bash: cd: /pod/pstore/groups/treehouse/for_core/THR10: Permission denied
-bash-4.2$

**Comment by klearned** [comment]
Shoot, I'll look into this.

**Comment by e-t-k** [comment]
@klearned Problem seems to be with the for_core directory; try `chmod g+x` to set it group executable (folders must be executable for a person to cd into them.)

**Comment by klearned** [comment]
@e-t-k Hi Ellen, I created a folder with hard links to our fastq files for upload to the Core. I think the permissions of the directory should allow others in the group to access the files in the directory, but they are getting "Permission denied". Do you have any ideas as to why or what I can do to fix this issue?
Here's the directory:
/pod/pstore/groups/treehouse/for_core/THR10

Here's the ls -l for that folder:
drwxrwsr-x 3 klearned treehouse  6144 Mar 10 10:52 THR10

**Comment by klearned** [comment]
Great, thanks @adurbin2. I have changed my umask settings, so hopefully this won't be a problem again!

**Comment by klearned** [comment]
Need to redact, convert from bam to fastq again with new btfv5, and reupload to Core.

**Comment by klearned** [comment]
Sent redaction request to Walt for these THR10 files.

**Comment by klearned** [comment]
Deleted old fastq files.
Started bam to fastq conversion with btfv5.

**Comment by klearned** [comment]
Possible naming bug in btfv5, emailed Linh.
