### ISSUE TITLE
Repository - EGAD00001001666 Low Grade Glioma Epilepsy RNA-seq

### ISSUE THREAD

**Issue by klearned** [UCSC-Treehouse/operations#27]
Original paper: [PMID 26810070](https://www.ncbi.nlm.nih.gov/pubmed/26810070)
From: St Jude (via EGA [EGAD00001001666](https://www.ebi.ac.uk/ega/datasets/EGAD00001001666) )
Detailed file spreadsheet: [EGAD00001001666 PCPG: Low Grade Glioma Epilepsy RNA-seq](https://docs.google.com/a/ucsc.edu/spreadsheets/d/11wjD8_3p4CK1X58Qs0as_UbMPnZKEICWjbpWfwZPSds/edit?usp=sharing)

n= 63 samples from 33 patients
paired-end

**Task List:**
- [x] Request permission
- [x] Download & decrypt data
- [x] Convert bam to fastq
- [ ] Treeshop (RNAseq Pipeline + QC)
- [ ] Medbook
- [ ] Tertiary analysis

**Important paper excerpts:**
>Abstract
>Low-grade neuroepithelial tumors (LGNTs) are diverse CNS tumors presenting in children and young adults, often with a history of epilepsy. While the genetic profiles of common LGNTs, such as the pilocytic astrocytoma and 'adult-type' diffuse gliomas, are largely established, those of uncommon LGNTs remain to be defined. In this study, we have used massively parallel sequencing and various targeted molecular genetic approaches to study alterations in 91 LGNTs, mostly from children but including young adult patients. These tumors comprise dysembryoplastic neuroepithelial tumors (DNETs; n = 22), diffuse oligodendroglial tumors (d-OTs; n = 20), diffuse astrocytomas (DAs; n = 17), angiocentric gliomas (n = 15), and gangliogliomas (n = 17). Most LGNTs (84 %) analyzed by whole-genome sequencing (WGS) were characterized by a single driver genetic alteration. Alterations of FGFR1 occurred frequently in LGNTs composed of oligodendrocyte-like cells, being present in 82 % of DNETs and 40 % of d-OTs. In contrast, a MYB-QKI fusion characterized almost all angiocentric gliomas (87 %), and MYB fusion genes were the most common genetic alteration in DAs (41 %). A BRAF:p.V600E mutation was present in 35 % of gangliogliomas and 18 % of DAs. Pathogenic alterations in FGFR1/2/3, BRAF, or MYB/MYBL1 occurred in 78 % of the series. Adult-type d-OTs with an IDH1/2 mutation occurred in four adolescents, the youngest aged 15 years at biopsy. Despite a detailed analysis, novel genetic alterations were limited to two fusion genes, EWSR1-PATZ1 and SLMAP-NTRK2, both in gangliogliomas. Alterations in BRAF, FGFR1, or MYB account for most pathogenic alterations in LGNTs, including pilocytic astrocytomas, and alignment of these genetic alterations and cytologic features across LGNTs has diagnostic implications. Additionally, therapeutic options based upon targeting the effects of these alterations are already in clinical trials.

> **Methods**
> **Sample series and processing**
> The study cohort comprised 91 primary cerebral LGNTs (Supp. Table S1), presenting in 48 (53 %) male and 43 (47 %) female patients, with a median age at surgery of 10 years (range 1–41 years). Three broad categories of LGNT were represented: (1) tumors with a dominant oligodendroglial phenotype—dysembryoplastic neuroepithelial tumors (DNETs, n = 22) and the diffuse oligodendroglial tumors (d-OTs, n = 20), oligodendrogliomas and oligoastrocytomas; (2) tumors with a dominant astrocytic phenotype—angiocentric gliomas (AGs, n = 15) and diffuse astrocytomas (DAs, n = 17), and (3) gangliogliomas (n = 17). The histopathological diagnosis was reviewed in each case (DWE). Fifty-nine samples were snap-frozen at the time of first resection. Thirty-two samples were available only as archived formalin-fixed paraffin wax-embedded (FFPE) material. Tumor and germline blood samples were processed according to starting material and as previously described (see Supplemental Methods and Supp. Fig. S1) [22, 67].

>**Supplemental**
>For transcriptome sequencing, polyA-enriched mRNA-Seq protocol was applied to RNA extracted frozen tissues, whereas RNA Access protocol was applied to RNA extracted from FFPE samples. Paired-end reads from RNA-seq were aligned to the following four databases using BurrowsWheeler Aligner (BWA 0.5.5) [6]: (i) human NCBI Build 37 reference sequence, (ii) RefSeq, (iii) a sequence file that represents all possible combinations of non-sequential pairs in RefSeq exons, and (iv) AceView flat file (UCSC), representing transcripts constructed from human ESTs. The mapping results were aligned to human reference genome coordinates, and final BAM files were constructed by selecting the best alignment, as previously described [9]. On average, 52% of exonic bases were covered to a depth of at least 20x. Mapping statistics and coverage for each RNA-seq sample are summarized in Supp. Table 2c. SV detection in RNA-seq was carried out using CICERO, a novel algorithm that uses de novo assembly to identify structural variations in RNA-seq data [9]. Results are reported in Supp. Table 8.

**Comment by adurbin2** [comment]
My notes indicate bam-to-fastq conversion is done (Linh email Dec 8).

**Comment by klearned** [comment]
@adurbin2 Actually, they haven't been converted yet. I want to get that to Linh, but I went down the clinical data rabbit hole and am just getting out :) I am going to send these to Linh to convert asap.

**Comment by adurbin2** [comment]
Oh sorry, I must have misunderstood an earlier email... Thanks for sending access - I will start marking up the worksheet for this one too.

**Comment by klearned** [comment]
Ya, I accidentally had Linh put files from another dataset in the fastq file for this dataset. So, at one point it looked like these had been converted. You were really paying attention!

**Comment by klearned** [comment]
@linhvoyo Please convert the 63 bam files listed in the following file into fastq files:
`/scratch/klearned/EgaDemoClient/EGAD00001001666/bamRna/fileListEGAD00001001666`

Please put the fastq files here:
`/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001001666/fastq`

Let me know if you have any questions!

**Comment by linhvoyo** [comment]
Hi Katrina.
I'm done. Everything is all there 
/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001001666/fastq

I changed the name to R1/R2 also.

**Comment by klearned** [comment]
Great! Thank you @linhvoyo !

**Comment by klearned** [comment]
@rcurrie The 63 samples are ready to be run through Treeshop. The manifest file is here:

`/pod/pstore/groups/treehouse/published-data/stjude/EGAD00001001666/fastq/manifestEGAD100001001666
`

**Comment by klearned** [comment]
@adurbin2 I have all the clinical data that I could find in fields in the spreadsheet. I wanted to capture it all, so I didn't try to fit it into your fields. It's all in there if you want to fit it into your fields for the index when you're ready. Thanks!

**Comment by adurbin2** [comment]
[401_2016_1539_MOESM1_ESM.pdf](https://github.com/UCSC-Treehouse/operations/files/661906/401_2016_1539_MOESM1_ESM.pdf)

I want to use this supplemental table to apply a more detailed diagnosis to the downloaded samples - will consult with Olena.

**Comment by klearned** [comment]
@adurbin2 Here is info about the other diagnosis abbreviations from the paper:

> AG angiocentric glioma, DA diffuse astrocytoma, DNET dysembryoplastic neuroepithelial tumor, O oligodendroglioma, OA oligoastrocytoma, GG ganglioglioma, Astro astrocytic, d-OT diffuse oligodendroglial tumor

**Comment by adurbin2** [comment]
Perfect, thank you. Now I will just work with Olena to make this fit the disease/histology/stage/grade/subcategory fields.

**Comment by klearned** [comment]
Great! Thank you Ann! Please let me know if you have any questions or need
me to do additional research/searching.

**Comment by adurbin2** [comment]
@rcurrie @cygao Hi guys - can we get an update on RNASeq for this set of samples?

**Comment by klearned** [comment]
@linhvoyo The fastqs for this dataset was converted between 12/14 and 12/19...do you think these had the unpaired reads bug? Do you think these need to be re-converted from bam to fastq like EGAD00001001098 (#22), which were also converted in early December?

**Comment by klearned** [comment]
@linhvoyo wondering if you saw my note above about the fastq files? The fastqs for this dataset was converted between 12/14 and 12/19...do you think these had the unpaired reads bug? Do you think these need to be re-converted from bam to fastq like EGAD00001001098 (#22), which were also converted in early December?

**Comment by linhvoyo** [comment]
@klearned sorry I missed your email. I think those might need to be re-converted. You can also just run them through and rerun those that failed. I think majority of them will pass

**Comment by adurbin2** [comment]
For QC purposes, it would be good to run all the samples through on the same version of the software.

**Comment by klearned** [comment]
reconverting the bams to fastqs because we think these were converted when there was a bug in the bam to fastq docker process.

**Comment by klearned** [comment]
Here is the manifest:
[EGAD00001001666](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1ncWEbj7aHtcrZqi8_Pb82lYSVRrbmwr-X9ONSwIF2jY/edit?usp=sharing)

@cygao I do have two questions (which we could wait to go over tomorrow, but I don't want to forget them!):
1) which Workflow versions are we using, spinnaker 1.0.2?
2) for file location, I have the current location on /pod in this column, but do I need to change that to dcc/data/filename like Rob had for EGAD00001001098?

**Comment by cygao** [comment]
@klearned 

1. Correct, we are currently using spinnaker 1.0.2
2. Correct, all file locations must be prepended with dcc/data/ (it is where the files are seen within the docker container). Rob's Google Sheets Manifests do this automatically, if you are using that as a template.

**Comment by klearned** [comment]
@cyago great, thanks!

**Comment by klearned** [comment]
@adurbin2 this [manifest](https://docs.google.com/spreadsheets/d/1ncWEbj7aHtcrZqi8_Pb82lYSVRrbmwr-X9ONSwIF2jY/edit#gid=217189623) is also now ready for Treehouse Ids. Thank you!

**Comment by adurbin2** [comment]
done! Needs hard links?

**Comment by klearned** [comment]
@adurbin2 Thanks! OK, I created the hard links:
/pod/pstore/groups/treehouse/for_core/THR11
So, these are ready to upload, too! I'll start the upload when the datasets queued up in front of it are done.

**Comment by klearned** [comment]
Started the upload!

**Comment by klearned** [comment]
Some of these files failed cutadapt even though I deleted all the original fastqs and re-converted them with the new V2 conversion docker ([see this comment above](https://github.com/UCSC-Treehouse/operations/issues/27#issuecomment-276894463)). See https://github.com/UCSC-Treehouse/operations/issues/23#issuecomment-286655451 for more info about the errors and the background.

**Comment by klearned** [comment]
Sent redaction request for files that failed cutadapt.
