### ISSUE TITLE
Repository - EGAD00001001016 PCGP Ph-like ALL RNA-seq

### ISSUE THREAD

**Issue by klearned** [UCSC-Treehouse/operations#39]
Original paper: [PMC4477877](http://europepmc.org/articles/PMC4477877)
From: St Jude (via EGA: [EGAD00001001016](https://www.ebi.ac.uk/ega/datasets/EGAD00001001016l) )
Detailed file spreadsheet: [EGAD00001001016 PCGP Ph-like ALL](https://docs.google.com/a/ucsc.edu/spreadsheets/d/1VL8f5w7wlmtLdpOVClRZMqDqJFRgQqR8QbM4Md4GxSk/edit?usp=sharingl)

126 patients (still figuring this out, there's an issue)
125 samples (still figuring this out, there's an issue)

**Task List:**
- [ ] Create Google spreadsheet
- [ ] Verify RNA-seq data
- [ ] Download data
- [ ] Convert bam to fastq
- [ ] Treeshop / CORE (RNAseq Pipeline + QC)

**Important paper excerpts:**
>**Abstract**
>text of abstract.

> **Methods**
> applicable text from Methods.

>**Supplemental**
>applicable text

**Comment by meesavag** [comment]
@klearned Do you want me to convert these files to fastq? Happy to do it

**Comment by klearned** [comment]
@meesavag thanks Meghan, but there is a bug in the bam to fastq docker. Linh and Holly are working on it, but last I heard, it's not ready yet. We shouldn't convert any more until they are ready. Once the new docker version is ready, we'll need to convert these and all the files that failed due to cutadapt errors in the Core. There will be lots to convert!
